---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: demo
spec:
  minReadySeconds: 8
  replicas: 2
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
        version: "2.0"  # Fixed label formatting
    spec:
      terminationGracePeriodSeconds: 30  # Best practice for graceful shutdown
      containers:
        - name: con-1
          image: shaikkhajaibrahim/dmtest:2.0
          ports:
            - containerPort: 80
              protocol: "TCP"
          readinessProbe:
            initialDelaySeconds: 3
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 2  # Added timeout
            httpGet:
              path: '/'
              port: 80
