---
apiVersion: v1
kind: Pod
metadata:
  name: activity-1
  labels:
    app: nop
    env: dev
    purpose: practice
spec:
  containers:
    - name: nop
      image: aravindh146/nopcommerece:v1.0
      ports:
        - containerPort: 5000
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "64Mi"

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:9
    env:
      - name: MYSQL_DATABASE
        value: db1
      - name: MYSQL_USER
        value: admin
      - name: MYSQL_PASSWORD
        value: admin1234
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306


---
apiVersion: v1
kind: Pod
metadata:
  name: activity-1
  labels:
    app: nop
    env: dev
    purpose: learning
spec:
  containers:
    - name: nop
      image: aravindh146/nopcommerece
      ports:
        - containerPort: 5000
          protocol: TCP
      resources: 
        limits: 
          cpu: "250m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
  

---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

