apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
spec:
  minReadySeconds: 40
  replicas: 2
  selector:
    matchLabels:
      app: spc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
        - name: spc-container
          image: shaikkhajaibrahim/spcjan2024:1.0 # Replace with actual image name
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 40
            periodSeconds: 10
