apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels: 
    app: mysqldb 
spec:
  containers:
    - name: container1
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin123"
        - name: MYSQL_DATABASE
          value: "Test"
        - name: MYSQL_USER
          value: "Ara"
        - name: MYSQL_PASSWORD
          value: "admin123"
      ports:
        - containerPort: 3386
          protocol: "TCP"
      volumeMounts:
        - name: sql-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: sql-vol
      persistentVolumeClaim:
        claimName: mysql-pvc


          