# Deployment definition in Kubernetes
apiVersion: apps/v1  # Specifies the API version for Deployments
kind: Deployment  # Defines the resource type as a Deployment
metadata:
  name: my-deployment  # Name of the Deployment
  labels:
    app: my-app  # Label for application identification
    environment: production  # Environment label (e.g., dev, staging, production)
spec:
  replicas: 3  # Number of desired Pod replicas
  selector:
    matchLabels:
      app: my-app  # Must match labels in template
  strategy:
    type: RollingUpdate  # Deployment strategy (RollingUpdate or Recreate)
    rollingUpdate:
      maxSurge: 1  # Maximum number of extra Pods during update
      maxUnavailable: 1  # Maximum number of unavailable Pods during update
  template:
    metadata:
      labels:
        app: my-app  # Labels assigned to Pods
        environment: production
    spec:
      restartPolicy: Always  # Restart policy (Always, OnFailure, Never)
      containers:
        - name: my-container  # Name of the container inside the Pod
          image: nginx:latest  # Container image to use (change as needed)
          ports:
            - containerPort: 80  # Port inside the container to expose
          resources:
            requests:
              cpu: "250m"  # Minimum CPU request
              memory: "256Mi"  # Minimum Memory request
            limits:
              cpu: "500m"  # Maximum CPU limit
              memory: "512Mi"  # Maximum Memory limit
          env:
            - name: ENVIRONMENT
              value: "production"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config  # Directory inside the container
      volumes:
        - name: config-volume
          emptyDir: {}  # Example empty directory volume