---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: webapp
        version: v3.0
    spec:
      containers:
        - name: webapp
          image: shaikkhajaibrahim/dmtest:3.0
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 80
              protocol: "TCP"
          readinessProbe:
            initialDelaySeconds: 3
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 5
            httpGet:
              path: '/'
              port: 80


