apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin123"
            - name: MYSQL_DATABASE
              value: "mydb"
            - name: MYSQL_USER
              value: "Ara"
            - name: MYSQL_PASSWORD
              value: "password123"
          ports:
            - containerPort: 3306
              protocol: TCP