apiVersion: v1
kind: Pod 
metadata:
  name: nodelabelpod
spec:
  containers:
    - name: con1
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
  nodeSelector:
    env: dev