apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: db
spec:
  containers:
    - name: db-container
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin123"
        - name: MYSQL_DATABASE
          value: "Ara"
        - name: MYSQL_USER
          value: "aravindh"
        - name: MYSQL_PASSWORD
          value: "admin123"
      volumeMounts:
        - name: test-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: mysql-pvc