--- 
apiVersion: v1
kind: Pod
metadata:
  name: nop-db
spec:
  containers:
    - name: nop
      image: mysql:latest
      args:
        - sleep
        - 1d
      volumeMounts:
        - name: configvolume
          mountPath: /config
  volumes:
    - name: configvolume
      configMap:
        name: nop-cm