apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nop-rs
  labels:
    app: nop
    component: frontend
    type: ReplicaSet
spec:
  minReadySeconds: 25
  replicas: 2
  selector:
    matchLabels:
      app: nop
  template:
    metadata:
      labels:
        app: nop
    spec:
      containers:
        - name: nop
          image: aravindh146/nopcommerece:v1.0
          ports:
            - containerPort: 5000
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: nop-service
  labels:
    app: nop
spec:
  type: LoadBalancer
  selector:
    app: nop
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
