apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels:
    app: spc
    component: frontend
    type: ReplicaSet
spec:
  minReadySeconds: 25
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
        - name: spc
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: spc-service
  labels:
    app: spc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
