apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  backoffLimit: 3 # if job fails how many times k8s should restart it
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: downloadjob
          image: alpine
          args:
            - sleep
            - 5s
      restartPolicy: "OnFailure"