apiVersion: v1
kind: Pod
metadata:
  name: activity2
  labels:
    env: dev
    app: nop
spec:
  initContainers:
    - name: pre-condition1
      image: alpine
      args:
        - sleep
        - 10s
    - name: pre-condition2
      image: alpine
      args:
        - sleep
        - 11s
  containers:
    - name: maincar
      image: nginx
      args:
        - sleep
        - 1d
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
        requests:
          cpu: "2500m"
          memory: "128Mi"
      ports:
        - containerPort: 80
    - name: sidecar
      image: alpine
      args:
        - sleep
        - 1d
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
        requests:
          cpu: "2500m"
          memory: "128Mi"
      ports:
        - containerPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: activity2
  labels:
    env: dev
    app: nop
spec:
  initContainers:
    - name: pre-condition1
      image: alpine
      args:
        - sleep
        - 10s
    - name: pre-condition2
      image: alpine
      args:
        - sleep
        - 11s
  containers:
    - name: maincar
      image: nginx
      args:
        - sleep
        - 1d
      ports:
        - containerPort: 80
    - name: sidecar
      image: alpine
      args:
        - sleep
        - 1d
      ports:
        - containerPort: 80
