--- # Pod
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: mycon1
      image: aravindh146/nginx-gym:1.0
      ports:
        - containerPort: 80
          protocol: TCP
--- # Service

apiVersion: v1
kind: Service
metadata:
  name: mypod-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: nginx
    

  
      