apiVersion: v1
kind: Service
metadata:
  name: my-normal-service
spec:
  type: ClusterIP  # Default service type
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80
