apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-deployment
spec:
  replicas: 2
  minReadySeconds: 40
  selector:
    matchLabels:
      app: nop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nop
    spec:
      containers:
        - name: nop-container
          image: aravindh146/nopcommerece:v1.0  # Ensure this image exists
          ports:
            - containerPort: 5000  # Matches the actual app port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/"
              port: 5000  # Corrected port to match the container's exposed port
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 40
            periodSeconds: 10
            